---
- hosts: "{{ playbook_dir | basename }}"
  become: yes
  pre_tasks:
    - name: Prep stuff for RedHat 6
      block:
        - yum: name=libselinux-python
        - yum: name=epel-release
        - yum: name={{ item }}
          with_items:
            - python-urllib3
            - python2-ndg_httpsclient
      when:
        - ansible_distribution_file_variety == "RedHat"
        - ansible_distribution_major_version == "6"
    - name: Prep stuff for Ubuntu 14
      block:
        - apt: name=python-pip update_cache=yes
        - pip: name=ndg-httpsclient state=present
      when:
        - ansible_distribution == "Ubuntu"
        - ansible_distribution_major_version == "14"
  roles:
    - ../{{ playbook_dir | basename }}
