---
- name: link config for openresty to nginx
  file:
    state: link
    src: "{{ openresty_conf_path }}"
    path: "{{ nginx_conf_path }}"

- debug: var=ansible_service_mgr

- name: link openresty init script as nginx for service
  file:
    state: link
    src: /etc/init.d/openresty
    path: /etc/init.d/nginx

- name: create nginx service for systemd
  template:
    src: etc/systemd/system/nginx.service.j2
    dest: /etc/systemd/system/nginx.service
    owner: root
    group: root
    mode: 0644
  when: ansible_service_mgr == 'systemd'

- name: create standard nginx directories
  file:
    state: directory
    path: "{{ nginx_conf_path }}/{{ item }}"
  with_items:
    - conf.d
    - sites-enabled
    - sites-available

- name: create standard nginx log directory
  file:
    state: directory
    path: "/var/log/nginx/"
