---
# Variable setup
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  tags: openresty_configure

# Setup/install tasks
- include: setup-RedHat.yml
  when: ansible_distribution == 'Red Hat Enterprise Linux'

- include: setup-CentOS.yml
  when: ansible_distribution == 'CentOS'

- include: setup-Fedora.yml
  when: ansible_distribution == 'Fedora'

- include: setup-Debian.yml
  when: ansible_distribution == 'Debian'

- include: setup-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

# Module tasks
- include: modules.yml
  tags: openresty_modules

# Configuration tasks
- include: configure.yml
  tags: openresty_configure